### ISSUE TITLE
Pre-trained models and ref. output files are unavailable

### ISSUE THREAD

**Issue by 1azyking** [AuroraLHT/cryspnet#10]
Sorry to bother you. The path of `/cryspnet/learner` and `/output` available are empty. Hence when I run:

```
python predict.py -i demo/demo.csv -o output/output.csv
```

It raises error like:

```
Traceback (most recent call last):
  File "PATH\TO\CRYSPNET\predict.py", line 81, in <module>
    main()
  File "PATH\TO\CRYSPNET\predict.py", line 52, in main
    BE = load_Bravais_models(
  File "PATH\TO\CRYSPNET\cryspnet\models.py", line 20, in load_Bravais_models
    BE = BravaisEnsembleModel.from_folder(str(models_dir), n=n_ensembler, batch_size=batch_size, cpu=cpu)
  File "PATH\TO\CRYSPNET\cryspnet\models.py", line 235, in from_folder
    if not folder.exists(): raise FileNotFoundError(str(folder))
FileNotFoundError: PATH\TO\CRYSPNET\cryspnet\learner\BravaisEsmWhole
```

Could you please offer your pre-trained models of `Bravais`, `Lattice`, and `SpaceGroup` so that I can directly utilize them to make prediction without any training? By the way, the output files corresponding to the demo files are also unavailable. There are only `.gitkeep` placeholder in these two paths. Thanks.

**Comment by AuroraLHT** [comment]
Hi, please download the learner from the link to [google drive](https://drive.google.com/file/d/1rpbV2-mnNj3M16-4BKvhuo5pkeoIY96q/view?usp=sharing). This zip file should contain the learner folder for all the pre-trained model.

**Comment by 1azyking** [comment]
Thanks for your sharing. I will try making predictions on your models. I think my issue is solved.
